from .horse import Horse

HORSE_POOL = [
    Horse(name="Destiny", step_probability=34, selection_weight=5),
    Horse(name="Beyoncé", step_probability=61, selection_weight=4),
    Horse(name="Jasmine", step_probability=52, selection_weight=5),
    Horse(name="Tumbleweed", step_probability=38, selection_weight=5),
    Horse(name="Fortune", step_probability=43, selection_weight=5),
    Horse(name="Medusa", step_probability=63, selection_weight=5),
    Horse(name="Boudicca", step_probability=66, selection_weight=3),
    Horse(name="Kentucky", step_probability=49, selection_weight=4),
    Horse(name="Firestorm", step_probability=28, selection_weight=5),
    Horse(name="Horsey McHorseFace", step_probability=50, selection_weight=1),
    Horse(name="Bilbo", step_probability=47, selection_weight=3),
    Horse(name="Chattanooga", step_probability=44, selection_weight=4),
    Horse(name="Babieca", step_probability=36, selection_weight=3),
    Horse(name="Jarosław", step_probability=45, selection_weight=3),
    Horse(name="Outback Steakhouse", step_probability=49, selection_weight=1),
    Horse(name="Flash", step_probability=57, selection_weight=5),
    Horse(name="Bolt", step_probability=56, selection_weight=5),
    Horse(name="Lightning", step_probability=54, selection_weight=5),
    Horse(name="Thunder", step_probability=55, selection_weight=5),
    Horse(name="Tuesday", step_probability=52, selection_weight=5),
    Horse(name="Friday", step_probability=54, selection_weight=5),
    Horse(name="Spirit", step_probability=64, selection_weight=5),
    Horse(name="Pegasus", step_probability=69, selection_weight=5),
    Horse(name="Fluttershy", step_probability=61, selection_weight=2),
    Horse(name="Applejack", step_probability=56, selection_weight=1),
    Horse(name="Twilight", step_probability=43, selection_weight=3),
    Horse(name="Rarity", step_probability=46, selection_weight=3),
    Horse(name="Pinkie Pie", step_probability=48, selection_weight=1),
    Horse(name="Rainbow Dash", step_probability=52, selection_weight=1),
    Horse(name="Hengest", step_probability=57, selection_weight=2),
    Horse(name="Horsa", step_probability=54, selection_weight=2),
    Horse(name="Shadow Fax", step_probability=71, selection_weight=3),
    Horse(name="Montgomery", step_probability=35, selection_weight=4),
    Horse(name="Streak", step_probability=54, selection_weight=5),
]
