from .horse import Horse

HORSE_POOL = [
    Horse(
        name="Destiny",
        step_probability=30,
        selection_weight=5,
    ),
    Horse(
        name="Beyoncé",
        step_probability=72,
        selection_weight=3,
    ),
    Horse(
        name="Jasmine",
        step_probability=48,
        selection_weight=5,
    ),
    Horse(
        name="Tumbleweed",
        step_probability=38,
        selection_weight=4,
    ),
    Horse(
        name="Fortune",
        step_probability=75,
        selection_weight=5,
    ),
    Horse(
        name="Medusa",
        step_probability=68,
        selection_weight=4,
    ),
    Horse(
        name="Kentucky",
        step_probability=45,
        selection_weight=4,
    ),
    Horse(
        name="Firestorm",
        step_probability=28,
        selection_weight=5,
    ),
    Horse(
        name="Horsey McHorseFace",
        step_probability=50,
        selection_weight=1,
    ),
    Horse(
        name="Bilbo",
        step_probability=90,
        selection_weight=2,
    ),
    Horse(
        name="Chattanooga",
        step_probability=44,
        selection_weight=4,
    ),
    Horse(
        name="Babieca",
        step_probability=25,
        selection_weight=5,
    ),
    Horse(
        name="Jarosław",
        step_probability=10,
        selection_weight=5,
    ),
    Horse(
        name="Outback Steakhouse",
        step_probability=60,
        selection_weight=1,
    ),
    Horse(
        name="Flash",
        step_probability=57,
        selection_weight=3,
    ),
    Horse(
        name="Bolt",
        step_probability=58,
        selection_weight=4,
    ),
    Horse(
        name="Lightning",
        step_probability=100,
        selection_weight=1,
    ),
    Horse(
        name="Thunder",
        step_probability=10,
        selection_weight=5,
    ),
    Horse(
        name="Friday",
        step_probability=70,
        selection_weight=5,
    ),
    Horse(
        name="Spirit",
        step_probability=64,
        selection_weight=5,
    ),
    Horse(
        name="Pegasus",
        step_probability=69,
        selection_weight=5,
    ),
    Horse(
        name="Fluttershy",
        step_probability=73,
        selection_weight=2,
    ),
    Horse(
        name="Hengest",
        step_probability=57,
        selection_weight=2,
    ),
    Horse(
        name="Horsa",
        step_probability=54,
        selection_weight=2,
    ),
    Horse(
        name="Shadow Fax",
        step_probability=71,
        selection_weight=3,
    ),
    Horse(
        name="Montgomery",
        step_probability=35,
        selection_weight=4,
    ),
    Horse(
        name="Streak",
        step_probability=54,
        selection_weight=5,
    ),
]
